### ISSUE TITLE
Validación del movimiento de las piezas

### ISSUE THREAD

**Issue by nicomagni** [nicomagni/chess#2]
- [ ] validar movimiento del peón.
- [x] validar movimiento del alfil.
- [ ] validar movimiento del torre.
- [x] validar movimiento del caballo.
- [ ] validar movimiento del reina .
- [x] validar movimiento del rey.

**Comment by nicomagni** [comment]
Falta validar que no halla piezas en el path y que en e end point no halla una del mismo color que la pieza que se esta moviendo.

**Comment by nicomagni** [comment]
Listas todas las validaciones, falta ver porque no anda bien la logica del peon y de la torre.

**Comment by lucila** [comment]
como le fue al peon con la torre?
